---
title: "Dashboard"
subtitle: "Homer Dashboard"
# Using Font Awesome icon instead of logo file
logo: "fas fa-rocket"
icon: "fas fa-rocket"

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"

# Optional message
message:
  style: "is-dark"
  title: "Welcome!"
  content: "Hermes Pi Control Center"

# Services
services:
  - name: "Monitoring"
    icon: "fas fa-chart-line"
    items:
      - name: "Grafana"
        icon: "fas fa-chart-area"  # Using FA icon instead of logo
        subtitle: "Metrics & Analytics"
        tag: "monitoring"
        url: "http://192.168.50.20:3000"
        target: "_blank"
      - name: "Speedtest Tracker"
        icon: "fas fa-tachometer-alt"  # Using FA icon instead of logo
        subtitle: "Internet Speed Monitoring"
        tag: "network"
        url: "http://192.168.50.20:8080"
        target: "_blank" 