version: "3.7"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # DHCP
      - "68:68/tcp" # DHCP
      - "68:68/udp" # DHCP
      - "8080:80/tcp"  # Web UI & DNS-over-HTTP/QUIC
      - "8443:443/tcp" # DNS-over-HTTPS/QUIC
      - "3000:3000/tcp" # Initial setup Web UI
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - adguard_network

networks:
  adguard_network:
    driver: bridge 